def raise_exception():
    print("{:d}".format([1, 2, 3]))
